{% set version = "4.7.0" %}

package:
  name: jupyter_core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-{{ version }}.tar.gz
  sha256: aa1f9496ab3abe72da4efe0daab0cb2233997914581f9a071e07498c6add8ed3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - pywin32  # [win]
    - traitlets

{% set skip_all = "not test_not_on_path and not test_path_priority" %}
{% set skip_win_py2k = " and not test_migrate_config" %}
{% set skip = skip_all %}  # [not(win and py2k)]
{% set skip = skip_all ~ skip_win_py2k %}  # [win and py2k]
test:
  requires:
    # - ipykernel
    - mock  # [py2k]
    - nose
    - pytest
    - pip
  commands:
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
    # - python -m pytest --pyargs jupyter_core -k "{{ skip }}"
    - pip check
  imports:
    - jupyter_core

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Core common functionality of Jupyter projects.
  dev_url: https://github.com/jupyter/jupyter_core
  doc_url: https://jupyter-core.readthedocs.io
  doc_source_url: https://github.com/jupyter/jupyter_core/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
    - bollwyvl
    - Carreau
