{% set version = "5.8.1" %}

package:
  name: jupyter_core
  version: {{ version }}

source:
  url: https://github.com/jupyter/jupyter_core/releases/download/v{{ version }}/jupyter_core-{{ version }}.tar.gz
  sha256: 0a5f9706f70e64786b75acba995988915ebd4601c8a52e534a40b51c95f59941

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.4
  run:
    - platformdirs >=2.5
    - python >=3.8
    - traitlets >=5.3

test:
  source_files:
    - tests
  imports:
    - jupyter_core
  requires:
    - pip
  commands:
    - pip check
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Core common functionality of Jupyter projects.
  dev_url: https://github.com/jupyter/jupyter_core
  doc_url: https://jupyter-core.readthedocs.io
  doc_source_url: https://github.com/jupyter/jupyter_core/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - blink1073
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
    - bollwyvl
    - Carreau
    - jasongrout
    - SylvainCorlay
