{% set version = "4.6.1" %}

package:
  name: jupyter_core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-{{ version }}.tar.gz
  sha256: a183e0ec2e8f6adddf62b0a3fc6a2237e3e0056d381e536d3e7c7ecc3067e244

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - traitlets

test:
  commands:
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
  imports:
    - jupyter_core
    - jupyter_core.utils

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: Core common functionality of Jupyter projects.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
