# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.9.0"
  python_check_max: "3.14"
  # linter doesn't like `if` in `host` for `noarch`
  arch_package: ${{ "pywin32" if noarch_platform == "win" else "python "}}

package:
  name: jupyter_core
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-core/jupyter_core-${{ version }}.tar.gz
  sha256: 5f8fba10cfc946fe1b4037e986458fc89430397207b21d741dc399d3d42951d4

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter = jupyter_core.command:main
      - jupyter-migrate = jupyter_core.migrate:main
      - jupyter-troubleshoot = jupyter_core.troubleshoot:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling >=1.4
  run:
    - __${{ noarch_platform }}
    - ${{ arch_package }}
    - platformdirs >=2.5
    - python >=${{ python_min }}
    - traitlets >=5.3
  run_constraints:
    - pywin32 >=300

tests:
  - python:
      imports: jupyter_core
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - pyproject.toml
        - tests/
      recipe:
        - run_test.py
    requirements:
      run:
        # `jupyter-troublehsoot` shells out to `pip` in test
        - pip
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - jupyter -h
      - jupyter-migrate -h
      - jupyter-troubleshoot --help
      - python run_test.py
  - downstream: ipython
  # #103: times out in `test_execution_state`: AssertionError: assert 'starting' == 'busy'
  # - downstream: jupyter_server
  # #103: v0 recipe
  # - downstream: jupyterlab
  # #103: needs updated build for `python_min: 3.10`
  # - downstream: nbconvert-core

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Core common functionality of Jupyter projects.
  homepage: https://jupyter.org
  repository: https://github.com/jupyter/jupyter_core
  documentation: https://jupyter-core.readthedocs.io

extra:
  recipe-maintainers:
    - blink1073
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
    - bollwyvl
    - Carreau
    - jasongrout
    - SylvainCorlay
