build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test_on_native_only: true
conda_build:
  pkg_format: '2'
abi_migration_branches:
  - 4.x
# `boa` seems to fail with `test/downstreams` with `local` JSON
# errors, but `conda` can't find some test dependencies
# build_with_mambabuild: false
