travis:
  secure:
    BINSTAR_TOKEN: V6/yjfQJR/RyVZy1M3tIW1xS7mUcyKy7IekJrIKF2QYgmj26wQ1mNkve4/tc5ntEtEGdoQQucZYrWc6sWtRnyH6nswKbibiuFWUesoV+IrnyyoNME66z67WMZi0UUfP7wpl4wQclYrwqOZQUhgffVVw8zX9hTLKzlkAvk9cgthiSr2AR8HCZYxWuSjQJWfDVOQA42dsRC34SI8214r32m7WKu9rV+FIQCM95s21O9E3Q7PpewWp3Tzx8Msk3/q9/MdO1F/KweOR+0z1RZ7Yt9gkkumZZ8V+Kczww748vq7d1ekKscQdwe6ixhWpjEvzhfZ4IsnLBh3kM0UNg40YcwyswKUdQvTD0G5NRrcyp6P6psnayuQRzUYr0B+sq0FV/skuTi1zVtkMcLf4icThk0bb5GTruWm2dhlXZyzpDFW66MaznSiXhoNDDfFGayE8rH/tL5mB+/PJiAmtyrrQkLDChCD2tm3Frf1oTuMe70qteaD7RRjAc1k6udSYSRvyL7ZPpeXM3SbJOatwRVa12Rq2+e4huqBwkt8Sk0gNbiDR6EfvGyJlfMBLyv6RdYsxUaPJNZHuFtAyjC7NOnDzoLzBQwyfw0L96biOsWYsK9eenkN5e/Pw2B3Xt7MVTEYnqcIJofsCjGHU3IMtbxtkEdJ7ai5GJNkOi7HTe9A7zNaU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
